# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: xenial

language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8-dev"
      env: TOXENV=py38

install: pip install -U tox

script: tox -e ${TOXENV}
