# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: xenial
language: python
python: "3.7"
before_install:
  - pip install poetry
install:
  - poetry install
script:
 - poetry run python --version
 - poetry run pytest
before_deploy:
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master
    tags: true
