# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: xenial
language: python
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8-dev"
      env: TOXENV=py38
before_install:
  - pip install poetry
install:
  - poetry install
script:
 - poetry run python --version
 - poetry run tox -e ${TOXENV}
before_deploy:
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master
    tags: true
