name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    name: Python ${{ matrix.python-version }}

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Install Dependencies
        run: mise run install

      - name: Lint
        run: uv run ruff check tests src

      - name: Format check
        run: uv run ruff format --check tests src

      - name: Type check
        run: uv run ty check src tests

      - name: Test with pytest
        run: mise run test
